env:

  global:

    - CC_TEST_REPORTER_ID=4be8804a0d2d4b7203a3c4e2496bdfed6e1efda5ba49d39a42b9438b3ab5fa74

language: python

python:
 - "3.6"

install:
  - "pip install -r requirements.txt"

before_script:
  
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
 
script: 
  - nosetests --with-coverage
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
 
after_success:
  - "coveralls"